# Permalinks
permalink: /:categories/:title/

# Setup
title:            The Exon Archives
tagline:          'A D&D Setting.'
description:      'An archive of all the lore on the homebrew fantasy setting Exon.'
url:              http://aakankshy.github.io/exon
baseurl:          /

author:
  name:           'Aakanksh Yadav'
  email:          'aakankshy@gmail.com'

paginate:         5

# Custom vars
github:
  repo: https://github.com/Aakankshy/exon
